#ifndef CONF_GAME_H_INCLUDED
#define CONF_GAME_H_INCLUDED

enum animate_building_t { AB_BASE, AB_CHASSIS, AB_ELECTRONICS, AB_NUCLEARS, AB_PHASERS, AB_CANNON, AB_MISSILES, AB_COUNT };
enum static_building_t { SB_WALL_1, SB_WALL_2, SB_WALL_3, SB_WALL_4, SB_TREE_1, SB_COUNT };

#endif // CONF_GAME_H_INCLUDED
